INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(1, 'Alas de sangre', 'Rebecca Yarros', '2023-11-02', 'Editorial Planeta', 'Fantasía romántica', 9788408279797, 'https://m.media-amazon.com/images/I/91UJR77PRFL._UF1000,1000_QL80_.jpg', 'Violet entra en la academia de jinetes de dragón, donde la supervivencia es incierta. Entre enemigos y secretos, deberá demostrar su valía para sobrevivir.', 5, true, true, 21.9);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(2, 'La mala costumbre', 'Alana S. Portero', '2023-03-01', 'Seix Barral', 'Narrativa contemporánea', 9788432242281, 'https://imagessl.casadellibro.com/a/l/t0/81/9788432242281.jpg', 'Una niña trans crece en el Madrid de los ochenta, enfrentando la incomprensión y la violencia. Una historia poderosa sobre identidad y resistencia.', 4, true, true, 18.5);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(3, 'Blackwater I. La riada', 'Michael McDowell', '2024-02-01', 'Blackie Books', 'Fantasía / Terror / Saga familiar', 9788419650566, 'https://imagessl.casadellibro.com/a/l/t0/66/9788419650566.jpg', 'Una misteriosa mujer aparece tras una riada en Perdido, Alabama. Su llegada desencadena oscuros acontecimientos que marcarán a la familia Caskey.', 4, true, true, 22.0);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(4, 'El abismo del olvido', 'Paco Roca y Rodrigo Terrasa', '2023-11-02', 'Astiberri Ediciones', 'Novela gráfica / Memoria histórica', 9788419558213, 'https://imagessl.casadellibro.com/a/l/t0/13/9788419558213.jpg', 'Una historia real sobre la búsqueda de un padre fusilado en la Guerra Civil. Un homenaje a la memoria y la justicia desde la ilustración.', 4, true, true, 20.95);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(5, 'Recupera tu mente, reconquista tu vida', 'Marian Rojas Estapé', '2024-03-06', 'Editorial Espasa', 'Autoayuda / Psicología', 9788467071961, 'https://imagessl0.casadellibro.com/a/l/s7/20/9788467071320.webp', 'Una guía para gestionar el estrés, la ansiedad y el malestar emocional. Herramientas prácticas para mejorar la salud mental y recuperar la paz interior.', 3, true, true, 19.9);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(6, 'Alas de hierro', 'Rebecca Yarros', '2024-06-20', 'Editorial Planeta', 'Fantasía romántica', 9788408283107, 'https://imagessl7.casadellibro.com/a/l/t5/06/9788408294306.jpg', 'Violet debe enfrentarse a nuevos desafíos en su segundo año en el Basgiath War College. La lucha por el poder y la verdad se intensifica.', 3, true, true, 23.5);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(7, 'Tres enigmas para la Organización', 'Eduardo Mendoza', '2024-02-14', 'Seix Barral', 'Novela de espionaje / Humor', 9788432242328, 'https://imagessl0.casadellibro.com/a/l/s7/50/9788408284550.webp', 'Una parodia del mundo del espionaje protagonizada por un detective singular. Una trama hilarante llena de giros y crítica social.', 3, true, true, 17.95);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(8, 'Baumgartner', 'Paul Auster', '2024-03-06', 'Seix Barral', 'Narrativa contemporánea', 9788432242298, 'https://imagessl.casadellibro.com/a/l/t0/98/9788432242298.jpg', 'Baumgartner lidia con la pérdida de su esposa mientras reflexiona sobre la vida y el tiempo. Una novela íntima sobre la vejez y el amor.', 3, true, true, 24.0);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(9, 'En agosto nos vemos', 'Gabriel García Márquez', '2024-03-06', 'Random House', 'Narrativa latinoamericana', 9788439739913, 'https://imagessl.casadellibro.com/a/l/t0/13/9788439739913.jpg', 'Cada agosto, una mujer viaja a una isla para visitar la tumba de su madre. Un relato inédito sobre la sensualidad, el deseo y el paso del tiempo.', 3, true, true, 21.5);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(10, 'Un animal salvaje', 'Joël Dicker', '2024-04-04', 'Alfaguara', 'Thriller / Misterio', 9788420463771, 'https://imagessl1.casadellibro.com/a/l/t5/41/9788420476841.jpg', 'Una familia aparentemente perfecta guarda oscuros secretos. Un robo en un supermercado desata una cadena de eventos inesperados y peligrosos.', 3, true, true, 22.95);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(11, 'Patria', 'Fernando Aramburu', '2016-09-06', 'Tusquets Editores', 'Narrativa contemporánea', 9788490663196, 'https://imagessl.casadellibro.com/a/l/t0/96/9788490663196.jpg', 'Una novela sobre el conflicto vasco a través de dos familias enfrentadas por la violencia de ETA.', 5, true, true, 22.9);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(12, 'Los asquerosos', 'Santiago Lorenzo', '2018-10-10', 'Blackie Books', 'Narrativa contemporánea',9788417552183, 'https://imagessl.casadellibro.com/a/l/t0/83/9788417552183.jpg', 'Un hombre se esconde en un pueblo abandonado y reflexiona sobre la sociedad actual.', 4, true, true, 20.0);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(13, 'Intemperie', 'Jesús Carrasco', '2013-01-17', 'Seix Barral', 'Ficción', 9788432215056, 'https://imagessl.casadellibro.com/a/l/t0/56/9788432215056.jpg', 'Un niño huye a través de una tierra árida en busca de libertad.', 4, true, true, 18.5);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(14, 'Ordesa', 'Manuel Vilas', '2018-01-04', 'Alfaguara', 'Autobiografía', '9788420433188', 'https://imagessl.casadellibro.com/a/l/t0/88/9788420433188.jpg', 'Reflexión sobre la vida, la familia y la muerte en un relato íntimo.', 5, true, true, 21.0);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(15, 'Lectura fácil', 'Cristina Morales', '2018-10-01', 'Anagrama', 'Narrativa experimental', 9788433998668, 'https://imagessl.casadellibro.com/a/l/t0/68/9788433998668.jpg', 'Cuatro mujeres con discapacidad intelectual comparten piso en Barcelona. Crítica mordaz al sistema.', 4, true, true, 18.0);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(16, 'El infinito en un junco', 'Irene Vallejo', '2019-08-19', 'Siruela', 'Ensayo', 9788417860790, 'https://imagessl.casadellibro.com/a/l/t0/90/9788417860790.jpg', 'Una historia de los libros desde la Antigüedad hasta nuestros días.', 5, true, true, 23.95);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(17, 'Las maravillas', 'Elena Medel', '2020-10-26', 'Anagrama', 'Narrativa social', 9788433999016, 'https://imagessl.casadellibro.com/a/l/t0/16/9788433999016.jpg', 'Historia de dos mujeres en busca de su lugar en un mundo desigual.', 4, true, true, 19.0);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(18, 'Sira', 'María Dueñas', '2021-04-14', 'Planeta', 'Ficción histórica', 9788408249288, 'https://imagessl.casadellibro.com/a/l/t0/88/9788408249288.jpg', "Continuación de 'El tiempo entre costuras'. Sira afronta nuevos retos tras la guerra.", 4, true, true, 22.9);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(19, 'Reina roja', 'Juan Gómez-Jurado', '2018-11-08', 'Ediciones B', 'Thriller', 9788466664416, 'https://imagessl.casadellibro.com/a/l/t0/16/9788466664416.jpg', 'Antonia Scott es la persona más inteligente del planeta... y también la más peligrosa.', 4, true, true, 21.9);
INSERT INTO libros (id, titulo, autor, fecha_de_publicacion, editorial, categoria, ISBN, portada, sinopsis, valoracion, visible, stock, precio) VALUES
(20, 'El castillo de Barbazul', 'Javier Cercas', '2022-10-05', 'Tusquets', 'Novela negra', 9788490668467, 'https://imagessl.casadellibro.com/a/l/t0/67/9788490668467.jpg', 'Melchor Marín se enfrenta a un nuevo caso en Mallorca mientras intenta huir de su pasado.', 4, true, true, 21.0);
